# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

projectionDepth <- function(dts, dt, directions, m, n, d, k, depths) {
    invisible(.Call(`_fdalite_projectionDepth`, dts, dt, directions, m, n, d, k, depths))
}

